version: '3'

services:
    nginx:
        container_name: php-knowledge-base-nginx
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public/dist:/var/www/php-knowledge-base/public/dist

    php-fpm:
        container_name: php-knowledge-base-php-fpm
        build:
            dockerfile: ./etc/docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/php-knowledge-base
            - ./public/dist:/var/www/php-knowledge-base/public/dist

    db:
        container_name: php-knowledge-base-db
        image: mysql:8
        env_file:
            - ./.env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - dbData:/var/lib/mysql

volumes:
    dbData:
